exclude: ^\.gitignore$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
      exclude: \.gitignore
    - id: check-case-conflict
    - id: end-of-file-fixer
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
      args:
        - --assume-in-merge
    - id: check-json
    - id: check-toml
    - id: check-yaml
      args:
        - --allow-multiple-documents
    - id: check-added-large-files
    - id: mixed-line-ending
      args:
        - --fix=auto
