---
- name: Ensure k3s config directory exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Setup master nodes
  ansible.builtin.import_tasks: masters.yml
  when: "'masters' in group_names"

- name: Setup workers nodes
  ansible.builtin.import_tasks: workers.yml
  when: "'workers' in group_names"
