---
- name: Add k3s configuration file
  ansible.builtin.template:
    dest: /etc/rancher/k3s/config.yaml
    src: config-server.yaml.j2
    owner: root
    group: root
    mode: 0640

- name: First node setup
  block:
    - name: Ensure the auto-deploy manifest directory exists
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Download kube-vip RBAC manifest
      ansible.builtin.get_url:
        url: https://kube-vip.io/manifests/rbac.yaml
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml
        owner: root
        group: root
        mode: 0644
    - name: Copy kube-vip DaemonSet manifest
      ansible.builtin.template:
        src: kube-vip.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/kube-vip-ds.yaml
        owner: root
        group: root
        mode: 0644
  run_once: true

- name: Install calico CNI plugin
  ansible.builtin.include_tasks: calico.yml
  when: (custom_cni_enabled) and (custom_cni == 'calico')
  run_once: true

- name: Install k3s using the provided script
  ansible.builtin.shell:
    cmd: "curl -sfL https://get.k3s.io | sh -"
    creates: /etc/init.d/k3s
