---
- name: Add cgroups to kernel options
  ansible.builtin.lineinfile:
    path: /etc/update-extlinux.conf
    regexp: '^default_kernel_opts='
    line: default_kernel_opts="quiet rootfstype=ext4 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
  notify:
    - rebuild bootloader
    - reboot

- name: install common packages
  ansible.builtin.package:
    name:
      - rsync
      - gzip
    state: present
